services:
  # --- Frontend -------------------------------------------
  web:
    build:
      context: .
      dockerfile: ./apps/web/dockerfile
    container_name: web
    ports:
      - '5173:5173'
    env_file:
      - ./apps/web/.env
    command: npm run dev -- --filter=web
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - challenge-network
    depends_on:
      - api-gateway

  # --- API Gateway ----------------------------------------
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/dockerfile
    container_name: api-gateway
    ports:
      - '3000:3000'
    env_file:
      - ./apps/api-gateway/.env
    command: npm run dev -- --filter=api-gateway
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - challenge-network
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
      auth-service:
        condition: service_started
      tasks-service:
        condition: service_started

  # --- Auth Service ---------------------------------------
  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/dockerfile
    container_name: auth-service
    ports:
      - '3002:3002'
    env_file:
      - ./apps/auth-service/.env
    command: npm run dev -- --filter=auth-service
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - challenge-network
    depends_on:
      db:
        condition: service_started

  # --- Tasks Service --------------------------------------
  tasks-service:
    build:
      context: .
      dockerfile: ./apps/tasks-service/dockerfile
    container_name: tasks-service
    ports:
      - '3003:3003'
    env_file:
      - ./apps/tasks-service/.env
    command: npm run dev -- --filter=tasks-service
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - challenge-network
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started

  # --- Notifications Service ------------------------------
  notifications-service:
    build:
      context: .
      dockerfile: ./apps/notifications-service/dockerfile
    container_name: notifications-service
    ports:
      - '3004:3004'
    env_file:
      - ./apps/notifications-service/.env
    command: npm run dev -- --filter=notifications-service
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - challenge-network
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started

  # --- Banco de Dados -------------------------------------
  db:
    image: postgres:16-alpine
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - challenge-network
    restart: always

  # --- Message Broker -------------------------------------
  rabbitmq:
    image: rabbitmq:3.13
    container_name: rabbitmq
    ports:
      - '5672:5672'   # Porta do AMQP
      - '15672:15672' # Porta da Interface de Gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - challenge-network
    restart: always

# --- Volumes e Redes --------------------------------------
volumes:
  postgres_data:
  rabbitmq_data:
  node_modules:

networks:
  challenge-network:
    driver: bridge